#!/usr/bin/env bash

# selvbetjening.aarhuskommune.dk branch
# Setup upstream with OS2Forms CORE
git remote add upstream https://github.com/OS2Forms/os2forms.git
git fetch
git reset --hard 5.1.0
git merge --no-ff origin/feature/maps-element-display
git checkout --theirs CHANGELOG.md
git add CHANGELOG.md
git commit -m "Merge remote-tracking branch 'origin/feature/maps-element-display' into selvbetjening.aarhuskommune.dk"
git merge --no-ff origin/fix/336-avoid-inheriting-data-on-page-transition
git checkout --theirs CHANGELOG.md
git add CHANGELOG.md
git commit -m "Merge remote-tracking branch 'origin/fix/336-avoid-inheriting-data-on-page-transition' into selvbetjening.aarhuskommune.dk"
git merge --no-ff origin/feature/add-first-middle-and-last-name-nemid-elements
git checkout --theirs CHANGELOG.md
git add CHANGELOG.md
git commit -m "Merge remote-tracking branch 'origin/feature/add-first-middle-and-last-name-nemid-elements' into selvbetjening.aarhuskommune.dk"
git merge --no-ff origin/feature/add-states-configuration-to-handlers
git checkout --theirs CHANGELOG.md
git add CHANGELOG.md
git commit -m "Merge remote-tracking branch 'origin/feature/add-states-configuration-to-handlers' into selvbetjening.aarhuskommune.dk"
git merge --no-ff origin/feature/move-digital-signature-configuration-to-handler
# Manually handle conflicts in modules/os2forms_digital_signature/os2forms_digital_signature.install
# git add modules/os2forms_digital_signature/os2forms_digital_signature.install
git checkout --theirs CHANGELOG.md
git add CHANGELOG.md
git commit -m "Merge remote-tracking branch 'origin/feature/move-digital-signature-configuration-to-handler' into selvbetjening.aarhuskommune.dk"


docker run --rm --volume .:/app itkdev/php8.4-fpm:latest sed --in-place '1i This is a hack so the CHANGELOG is messed up. \nGenerated by build_release.sh' CHANGELOG.md
git add CHANGELOG.md
git commit -m "Updated CHANGELOG"
